---
  MuranoEnvironments.create_and_delete_environment:
    -
      runner:
        type: "constant"
        times: {{ compute * 200 if not super_light else super_light_count }}
        concurrency: {{ concurrency if not super_light else super_light_concurrency }}
      context:
        users:
          tenants: {{ compute * 20 if not super_light else super_light_concurrency }}
          users_per_tenant: 2
