---
version: 2
title: Create, rollout and delete deployment with random name
subtasks:
- title: Run a single workload with create/rollout/delete deployment
  scenario:
    Kubernetes.create_rollout_and_delete_deployment:
      image: busybox
      replicas: 3
      command:
      - sleep
      - "3600"
      env:
      - name: "UPD"
        value: "false"
      changes:
        env:
        - name: "UPD"
          value: "true"
  runner:
    constant:
      concurrency: {{ concurrency if not super_light else super_light_concurrency }}
      times: {{ compute * 5 if not super_light else super_light_count * 5 }}
  contexts:
    namespaces:
      count: 4
      with_serviceaccount: true
    kubernetes.cfg:
      prepoll_delay: 0
      retries_total: {{ compute * 45 if not super_light else super_light_count * 45 }}
      sleep_time: 1
- title: Run create/rollout/delete deployment with rps runner
  scenario:
    Kubernetes.create_rollout_and_delete_deployment:
      image: busybox
      replicas: 3
      command:
      - sleep
      - "3600"
      env:
      - name: "UPD"
        value: "false"
      changes:
        env:
        - name: "UPD"
          value: "true"
  runner:
    rps:
      rps: {{ concurrency if not super_light else super_light_concurrency }}
      times: {{ compute * 5 if not super_light else super_light_count * 5 }}
  contexts:
    namespaces:
      count: 4
      with_serviceaccount: true
    kubernetes.cfg:
      prepoll_delay: 0
      retries_total: {{ compute * 45 if not super_light else super_light_count * 45 }}
      sleep_time: 1
