---
  Kubernetes.create_and_delete_pod_with_configmap_volume:
  -
    args:
      image: busybox
      command:
      - "sleep"
      - "3600"
      mount_path: /var/log/check.txt
      subpath: check.txt
      configmap_data:
        check.txt: |
          test
      check_cmd:
      - ls
      - /var/log/check.txt
      error_regexp: No such file
    runner:
      type: constant
      concurrency: {{ concurrency if not super_light else super_light_concurrency }}
      times: {{ 30 if not super_light else super_light_count * 2 }}
    context:
      kubernetes.namespaces:
        count: 4
        with_serviceaccount: yes
      kubernetes.cfg:
        prepoll_delay: 3
        retries_total: {{ concurrency * 60 if not super_light else super_light_concurrency * 60 }}
        sleep_time: 1
    sla:
      failure_rate:
        max: 0
  -
    args:
      image: busybox
      command:
      - "sleep"
      - "3600"
      mount_path: /var/log/check.txt
      subpath: check.txt
      configmap_data:
        check.txt: |
          test
      check_cmd:
      - ls
      - /var/log/check.txt
      error_regexp: No such file
    runner:
      type: rps
      rps: {{ concurrency if not super_light else super_light_concurrency }}
      times: {{ 30 if not super_light else super_light_count * 2 }}
    context:
      kubernetes.namespaces:
        count: 4
        with_serviceaccount: yes
      kubernetes.cfg:
        prepoll_delay: 4
        retries_total: {{ 600 if not super_light else super_light_count * 20 }}
        sleep_time: 1
    sla:
      failure_rate:
        max: 0
