---
version: 2
title: Create, read, check and delete pod with configMap volume
subtasks:
- title: Run a single workload with create/read/check/delete pod with configMap volume
  scenario:
    Kubernetes.create_and_delete_pod_with_configmap_volume:
      image: {{ image_busybox }}
      command:
      - "sleep"
      - "3600"
      mount_path: /var/log/check.txt
      subpath: check.txt
      configmap_data:
        check.txt: |
          test
      check_cmd:
      - cat
      - /var/log/check.txt
      error_regexp: No such file
  runner:
    constant:
      concurrency: {{ concurrency if not super_light else super_light_concurrency }}
      times: {{ compute * 2 if not super_light else super_light_count * 2 }}
  contexts:
    namespaces:
      count: 3
      with_serviceaccount: true
      serviceaccount_delay: 5
    kubernetes.cfg:
      prepoll_delay: 1
      retries_total: {{ compute * 60 if not super_light else super_light_count * 60 }}
      sleep_time: 1
- title: Run create/read/check/delete pod with configMap volume with rps runner
  scenario:
    Kubernetes.create_and_delete_pod_with_configmap_volume:
      image: {{ image_busybox }}
      command:
      - "sleep"
      - "3600"
      mount_path: /var/log/check.txt
      subpath: check.txt
      configmap_data:
        check.txt: |
          test
      check_cmd:
      - cat
      - /var/log/check.txt
      error_regexp: No such file
  runner:
    rps:
      rps: {{ concurrency if not super_light else super_light_concurrency }}
      times: {{ compute * 2 if not super_light else super_light_count * 2 }}
  contexts:
    namespaces:
      count: 3
      with_serviceaccount: true
      serviceaccount_delay: 5
    kubernetes.cfg:
      prepoll_delay: 1
      retries_total: {{ compute * 60 if not super_light else super_light_count * 60 }}
      sleep_time: 1
