---
  Kubernetes.create_and_delete_configmap_volume:
  -
    args:
      image: busybox
      command:
      - "sleep"
      - "3600"
      mount_path: /var/log/check.txt
      subpath: check.txt
      sleep_time: 1
      retries_total: 40
      configmap_data:
        check.txt: |
          test
    runner:
      type: constant
      concurrency: {{ concurrency if not super_light else super_light_concurrency }}
      times: {{ compute * 5 if not super_light else super_light_count * 5 }}
    context:
      kubernetes.namespaces:
        count: 3
        with_serviceaccount: yes
      kubernetes.cfg:
        prepoll_delay: 0
        retries_total: {{ compute * 45 if not super_light else super_light_count * 45 }}
        sleep_time: 1
    sla:
      failure_rate:
        max: 0
  -
    args:
      image: busybox
      command:
      - "sleep"
      - "3600"
      mount_path: /var/log/check.txt
      subpath: check.txt
      sleep_time: 1
      retries_total: 40
      configmap_data:
        check.txt: |
          test
    runner:
      type: rps
      rps: {{ concurrency if not super_light else super_light_concurrency }}
      times: {{ compute * 5 if not super_light else super_light_count * 5 }}
    context:
      kubernetes.namespaces:
        count: 3
        with_serviceaccount: yes
      kubernetes.cfg:
        prepoll_delay: 0
        retries_total: {{ compute * 45 if not super_light else super_light_count * 45 }}
        sleep_time: 1
    sla:
      failure_rate:
        max: 0
